// <auto-generated />
namespace NITASA.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addonlayoutadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addonlayoutadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201506290740337_addon-layout-added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
